import {
  FiSettings, FiUsers, FiTruck, FiMap, FiBell,
  FiUser, FiShield, FiTag,
  FiMessageSquare, FiFileText, FiDollarSign,
  FiSend, FiAlertCircle, FiCreditCard, FiSliders,
  FiTrendingUp, FiActivity, FiRadio,
} from 'react-icons/fi'
import {
  MdOutlineLocalTaxi, MdOutlineDeliveryDining,
  MdOutlineSpaceDashboard,
} from 'react-icons/md'

export const menu = [
  {
    id: 'dashboard',
    label: 'Tableau de bord',
    icon: <MdOutlineSpaceDashboard size={17} />,
    path: '/dashboard',
  },
  { id: 'sep-setup', type: 'section', label: 'SETUP OBLIGATOIRE' },
  {
    id: 'config-base',
    label: 'Configuration de base',
    icon: <FiSettings size={16} />,
    children: [
      { id: 'countries', label: 'Pays', path: '/setup/countries' },
      { id: 'documents', label: 'Documents', path: '/setup/documents' },
      { id: 'services', label: 'Prestations', path: '/setup/services' },
      { id: 'zones', label: 'Zone de service', path: '/setup/zones' },
      { id: 'banners', label: 'Gestion des banni\u00e8res', path: '/setup/banners' },
      { id: 'weight-units', label: 'Weight Unit', path: '/setup/weight-units' },
      { id: 'map-markers', label: 'Map Markers', path: '/setup/map-markers' },
      { id: 'pricing-params', label: 'Pricing Parameters', path: '/setup/pricing-params' },
    ],
  },
  {
    id: 'carte-prix',
    label: 'Carte de prix',
    icon: <FiDollarSign size={16} />,
    children: [
      {
        id: 'taxi-logistics',
        label: 'Services de taxi et de logistique',
        children: [
          { id: 'pricecards', label: "Pour l'utilisateur & Conducteur", path: '/setup/pricecards' },
        ],
      },
    ],
  },
  {
    id: 'promo-codes',
    label: 'Code promo',
    icon: <FiTag size={16} />,
    path: '/setup/promo-codes',
  },
  { id: 'sep-dispatch', type: 'section', label: 'MANUAL DISPATCH' },
  {
    id: 'manual-dispatch',
    label: 'Manual Dispatch',
    icon: <FiSend size={16} />,
    path: '/dispatch/manual',
  },
  { id: 'sep-delivery', type: 'section', label: 'DELIVERY MANAGEMENT' },
  {
    id: 'delivery-mgmt',
    label: 'Delivery Management',
    icon: <MdOutlineDeliveryDining size={17} />,
    children: [
      { id: 'del-products', label: 'Products', path: '/delivery/products' },
    ],
  },
  {
    id: 'delivery-rides',
    label: 'Rides',
    icon: <FiTruck size={16} />,
    children: [
      { id: 'del-active', label: 'Randonn\u00e9es en cours', path: '/delivery/rides/active' },
      { id: 'del-completed', label: 'Completed Rides', path: '/delivery/rides/completed' },
      { id: 'del-cancelled', label: 'Cancelled Rides', path: '/delivery/rides/cancelled' },
      { id: 'del-failed', label: 'Failed Rides', path: '/delivery/rides/failed' },
      { id: 'del-auto-cancelled', label: 'Auto Cancelled Rides', path: '/delivery/rides/auto-cancelled' },
      { id: 'del-all', label: 'All Rides', path: '/delivery/rides/all' },
    ],
  },
  { id: 'sep-taxi', type: 'section', label: 'GESTION DES TAXIS' },
  {
    id: 'taxi-rides',
    label: 'Rides',
    icon: <MdOutlineLocalTaxi size={17} />,
    children: [
      { id: 'taxi-active', label: 'Randonn\u00e9es en cours', path: '/taxi/rides/active' },
      { id: 'taxi-completed', label: 'Completed Rides', path: '/taxi/rides/completed' },
      { id: 'taxi-cancelled', label: 'Cancelled Rides', path: '/taxi/rides/cancelled' },
      { id: 'taxi-failed', label: 'Failed Rides', path: '/taxi/rides/failed' },
      { id: 'taxi-auto-cancelled', label: 'Auto Cancelled Rides', path: '/taxi/rides/auto-cancelled' },
      { id: 'taxi-all', label: 'All Rides', path: '/taxi/rides/all' },
    ],
  },
  { id: 'sep-drivers', type: 'section', label: 'GESTION DES CONDUCTEURS' },
  {
    id: 'conducteurs',
    label: 'Conducteurs',
    icon: <FiUser size={16} />,
    children: [
      { id: 'dr-all', label: 'Tous les conducteurs', path: '/drivers/all' },
      { id: 'dr-status', label: 'Conducteur Statuts', path: '/drivers/status' },
      { id: 'dr-vehicle', label: 'Conducteurs en v\u00e9hicule', path: '/drivers/vehicle-based' },
      { id: 'dr-add', label: 'Ajouter un conducteur', path: '/drivers/add' },
      { id: 'dr-signup', label: 'Inscription de base', path: '/drivers/basic-signup' },
      { id: 'dr-pending', label: "En attente d'approbation", path: '/drivers/pending' },
      { id: 'dr-rejected', label: 'Conducteurs rejet\u00e9s', path: '/drivers/rejected' },
      { id: 'dr-temp', label: 'Temporairement rejet\u00e9s', path: '/drivers/temp-rejected' },
      { id: 'dr-online', label: 'Rapport en ligne du conducteur', path: '/drivers/online-report' },
      { id: 'dr-expiring', label: "Documents proche d'expiration", path: '/drivers/expiring-docs' },
      { id: 'dr-expired', label: 'Document expir\u00e9', path: '/drivers/expired-docs' },
    ],
  },
  {
    id: 'vehicles',
    label: 'V\u00e9hicules',
    icon: <FiTruck size={16} />,
    children: [
      { id: 'veh-all', label: 'Tous les v\u00e9hicules', path: '/drivers/vehicles' },
    ],
  },
  {
    id: 'drivers-map',
    label: 'Map',
    icon: <FiMap size={16} />,
    children: [
      { id: 'map-drivers', label: 'Carte des conducteurs', path: '/drivers/map' },
      { id: 'map-heat', label: 'Carte thermique', path: '/drivers/heatmap' },
    ],
  },
  { id: 'sep-users', type: 'section', label: 'GESTION DES UTILISATEURS' },
  {
    id: 'users',
    label: 'Utilisateurs',
    icon: <FiUsers size={16} />,
    path: '/users',
  },
  { id: 'sep-support', type: 'section', label: 'SYST\u00c8ME DE SUPPORT' },
  {
    id: 'sos',
    label: 'SOS',
    icon: <FiAlertCircle size={16} />,
    children: [
      { id: 'sos-number', label: 'Num\u00e9ro SOS', path: '/support/sos' },
      { id: 'sos-requests', label: 'Demande Sos', path: '/support/sos-requests' },
    ],
  },
  {
    id: 'customer-service',
    label: 'Service client',
    icon: <FiMessageSquare size={16} />,
    path: '/support/customer-service',
  },
  { id: 'sep-autre', type: 'section', label: 'AUTRE' },
  {
    id: 'content',
    label: 'Gestion de contenu',
    icon: <FiFileText size={16} />,
    children: [
      { id: 'cnt-pages', label: 'Pages', path: '/content/pages' },
      { id: 'cnt-cms', label: 'Pages CMS', path: '/content/cms' },
      { id: 'cnt-strings', label: "Cha\u00eenes d'application", path: '/content/app-strings' },
      { id: 'cnt-strings2', label: "Cha\u00eenes d'application v2", path: '/content/app-strings-v2' },
      { id: 'cnt-admin-str', label: "Cha\u00eenes d'admin", path: '/content/admin-strings' },
      { id: 'cnt-payment', label: 'Option de paiement', path: '/content/payment-options' },
    ],
  },
  {
    id: 'promotions',
    label: 'Notification promotionnelle',
    icon: <FiBell size={16} />,
    path: '/content/promotions',
  },
  {
    id: 'wallet',
    label: 'Recharge de portefeuille',
    icon: <FiCreditCard size={16} />,
    path: '/content/wallet-recharge',
  },
  { id: 'sep-transactions', type: 'section', label: 'GESTION DES TRANSACTIONS' },
  {
    id: 'withdrawal',
    label: 'Demande de retrait',
    icon: <FiDollarSign size={16} />,
    children: [
      { id: 'cashout', label: 'Conducteur', path: '/transactions/cashout' },
    ],
  },
  { id: 'sep-reports', type: 'section', label: 'RAPPORT ET GRAPHIQUES' },
  {
    id: 'rapports',
    label: 'Rapports & Analytics',
    icon: <FiTrendingUp size={16} />,
    children: [
      { id: 'rpt-financial',  label: 'Rapport financier',     path: '/reports/financial'  },
      { id: 'rpt-operations', label: 'Rapport opérationnel',  path: '/reports/operations' },
      { id: 'rpt-drivers',   label: 'Rapport conducteurs',   path: '/reports/drivers'    },
      { id: 'rpt-live',      label: '🔴 Tableau de bord live', path: '/reports/live'     },
    ],
  },
  { id: 'sep-params', type: 'section', label: 'PARAM\u00c8TRE' },
  {
    id: 'sous-admin',
    label: 'Sous-administrateur',
    icon: <FiShield size={16} />,
    children: [
      { id: 'admins', label: 'Liste des administrateurs', path: '/settings/admins' },
      { id: 'roles', label: 'R\u00f4le', path: '/settings/roles' },
    ],
  },
  {
    id: 'parametrage',
    label: 'Param\u00e9trage et configuration',
    icon: <FiSliders size={16} />,
    children: [
      { id: 'set-general', label: 'G\u00e9n\u00e9ral', path: '/settings/general' },
      { id: 'set-booking', label: 'Demande de configuration', path: '/settings/booking' },
      { id: 'set-driver', label: 'Configuration du conducteur', path: '/settings/driver' },
      { id: 'set-email', label: 'Configuration des e-mails', path: '/settings/email' },
      { id: 'set-email-tpl', label: 'Email Template', path: '/settings/email-template' },
      { id: 'set-svc-type', label: 'Configuration de type de service', path: '/settings/service-type' },
      { id: 'set-nav', label: 'Tiroir de navigation', path: '/settings/navigation-drawer' },
      { id: 'set-app-url', label: 'Application Url', path: '/settings/app-url' },
      { id: 'set-push', label: 'Configuration des notifications push', path: '/settings/push-notifications' },
      { id: 'set-cancel', label: "Raisons d'annulation", path: '/settings/cancel-reasons' },
      { id: 'set-payment', label: 'M\u00e9thode de paiement', path: '/settings/payment-method' },
    ],
  },
]
